MinimumStatiqDocsVersion-Docable: "1.0.0-beta.2"
GatherHeadingsLevel: 3
SiteTitle: Documentation
ApiLayout: Api/_ApiLayout
FontLink: ""
PostSources: posts/**/*
IsPost: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
