MinimumStatiqDocsVersion-Verdoct: "1.0.0-beta.8"
GatherHeadingsLevel: 3
SiteTitle: Documentation
ApiLayout: Api/_ApiLayout
FontLink: ""
HideTypeDiagrams: false
PostSources: posts/**/*
IsPost: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
